version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=DevPwd*123
    ports: ["1433:1433"]

  api:
    build:
      context: .          # use the Dockerfile we just wrote
      dockerfile: Eyewear.Shop.API/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=db,1433;Database=EyewearDb;User Id=Eyewear.Shop;Password=RezaEyewear;TrustServerCertificate=true
    ports: ["8080:8080"]
